---
- name: restart samba-ad-dc
  ansible.builtin.systemd:
    name: samba-ad-dc
    state: restarted
    daemon_reload: yes

- name: restart krb5-kdc
  ansible.builtin.systemd:
    name: krb5-kdc
    state: restarted
  ignore_errors: yes

- name: restart bind9
  ansible.builtin.systemd:
    name: bind9
    state: restarted
  ignore_errors: yes