---
collections:
  - name: community.general
    version: ">=7.0.0"
    source: https://galaxy.ansible.com
  - name: community.windows
    version: ">=2.0.0"
    source: https://galaxy.ansible.com
  - name: ansible.posix
    version: ">=1.5.0"
    source: https://galaxy.ansible.com
  - name: community.docker
    source: https://galaxy.ansible.com
  - name: community.postgresql
    source: https://galaxy.ansible.com
  - name: community.mysql
    source: https://galaxy.ansible.com
  - name: community.crypto
    source: https://galaxy.ansible.com
  - name: community.zabbix
    source: https://galaxy.ansible.com
  - name: prometheus.prometheus
    source: https://galaxy.ansible.com

roles:
  - name: geerlingguy.nginx
    version: "3.1.4"
  - name: geerlingguy.postgresql
    version: "3.5.2"
  - name: geerlingguy.certbot
    version: "5.1.0"
  - name: geerlingguy.firewall
    version: "2.5.0"
  - name: geerlingguy.security
    version: "2.0.0"